- name: Determine the current root device for the node
  ansible.builtin.set_fact:
    curr_root_dev: "{{ ansible_mounts | json_query('[?mount == `/`].device') | first }}"

- name: Move the root partition for the node to {{ root_dev }}
  when: not curr_root_dev.startswith(root_dev)
  become: true
  block:
    - name: Update ubuntu-rockchip-settings
      ansible.builtin.apt:
        name: ubuntu-rockchip-settings
        state: latest
      become: true

    - name: Execute ubuntu-rockchip-install
      ansible.builtin.shell: |
        yes | ubuntu-rockchip-install {{ root_dev }}
      become: true

    - name: Reboot the node
      ansible.builtin.reboot:
      become: true
