- name: Install client tools in execution environment
  hosts: localhost
  roles:
    - role: tools
  tags: tools

- name: Bare metal provisioning of turing_pi nodes
  hosts: turing_pis
  gather_facts: false
  roles:
    - role: flash
      when: do_flash
  tags: flash

- name: Make sure known_hosts is up to date
  hosts: all_nodes, turing_pis
  # only gather facts after the nodes are added to known_hosts
  gather_facts: false
  serial: 1
  roles:
    - role: known_hosts
  tags: known_hosts

- name: Update all nodes in preparation for k3s
  hosts: all_nodes # all nodes in all turing pi groups and outside
  roles:
    - role: move_fs
    - role: update_packages
  become: true
  tags: servers

- name: Install or update k3s control plane and workers
  hosts: all_nodes # all nodes in all turing pi groups and outside
  roles:
    - role: k3s
  become: true
  tags: k3s

- name: Install cluster services
  hosts: localhost
  roles:
    - role: cluster
  tags: cluster
