- name: Check dependencies
  ansible.builtin.include_tasks: dependencies.yml

- name: Install the chart for Grafana and Prometheus
  kubernetes.core.helm:
    chart_repo_url: https://prometheus-community.github.io/helm
    chart_ref: kube-prometheus-stack
    release_name: grafana-prometheus
    create_namespace: true
    force: "{{ cluster_force }}"
    namespace: monitoring
    values: "{{ lookup('template', 'grafana_values.yaml') | from_yaml }}"
  retries: 1
  delay: 10
