- name: Restart ArgoCD application controller
  ansible.builtin.command: >
    kubectl rollout restart -n argo-cd statefulset argocd-application-controller
  changed_when: true

- name: Restart Dex server
  ansible.builtin.command: >
    kubectl rollout restart -n argo-cd deployment argocd-dex-server
  changed_when: true

- name: Restart ArgoCD server
  ansible.builtin.command: >
    kubectl rollout restart -n argo-cd deployment argocd-server
  changed_when: true
