apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  claimRef:
    namespace: open-webui
    name: open-webui
  local:
    path: /var/lib/k8s-data/open-webui
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node04
