apiVersion: v1
kind: PersistentVolume
metadata:
  name: supabase-storage-local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  claimRef:
    namespace: supabase
    name: supabase-storage
  local:
    path: /home/k8s-data/supabase-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nuc2
