{{- range $name, $pv := .Values.local_storage }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name | replace "_" "-" }}-local
spec:
  capacity:
    storage: {{ $pv.capacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-nvme
  claimRef:
    namespace: {{ $pv.claim_namespace }}
    name: {{ $pv.claim_name }}
  local:
    path: {{ $pv.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ $pv.node }}
{{- end }}
