---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgDN1Nr7PqaVX/285xF6fHb0aKpcRWlSfTOCYasTdtCtlZ0mpbtTqZkCd8S6w2lj2hqP2sezAmjfd8y0Ms+V8DbxIXxRdgaSKgzQwZRG8nVAe8zoWaUn6GbdI50n/o4AkJqvdgbCGqTTj71OzpMifEF2z7HYgLmZFGewaZ0Tw/ivaE1WRTCgwjhlYq+7b5aXjFG4hYPcfNrqnf9x1+oteTMog1Po2ehkqcccXJqE9dyYzIMW4M5VdKTamD6kWSkiqRfD4TnYJzcpiR7RgY0nblcc9v4vghVR29INJfoZCxROdGnIhLeiR5kGDgb5IMWgQwnwrgx7AjAal1rDOvcwe8Ylal6nt//JBAgzHjinKxqDONTdXgdkuCHWjRhdG8CQPpEeI0SST610VGXd4hn7mL1nNMX+jANpKsCt7lQfgxiHsnc4yMGIHDzuG4Kd1tBIzzDhr/ZojCj20KPKuIvqarahAHBZejKJOQwFmL5DUnlHfLjGgQsHXin37QIbMTiI2aYUlS9CDKO9ZpDcHROSbuFA7/LDtdxggLOkUB5wBgMU6GUIgRLuW0EnNKE2dwBURKh7aLUMddIbu9KgKF/jgRT57hlCIbfzi+0lo/rcg1mJZPg/e0qRZS4bRe1seb65iJwXdR0PrKPO/FSomxdT+pRIgAq49NWN4SQnAkbpoEF15wFf08Uh4g6xfuSJsEiFw6W4zYd/4Ix79P/B9uWq+gJg/ULjdoFbL+y9Ocp0v5B2Ub31jl/gxbOH5RM5JQo1ah06vkbpsHykDfRoMMYW+PPbi5V6bBTZaHqjsm2fBQDHCfI=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
