---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgAm1/2gUeg1WjpQRmMAt1aEFfjn3PSOorZsNE70BPJpkwvir6FiRil5yr4rWvCiVlS83KXILFcvbQ+Nij5Fl7YnnWDXLNuK1r/L3Pv7A32wGL+SXQmCXcWoyhAzHdsGNgkqOxAQI/zu2iN9g2a4/V2rIzLdNQrg2sv9mpBrVktoXcwFADTTfdSo5FOLJuvNipOOew3AtannbBeA/htZcAsO7O0UiP0f7YI47FHkqInWG0gGWejHDgDwhs7rhOx+7s2EMHDdEny8fO8whEMH7oE9xGe8cQcWFVcjpMrIMkg6t58g9lOpywJkood60LuycWAreTRDZyOcpbjkDSxusC1acMNywlPDWQuYhZlqISVU4/wU0yzaJaiwj9gj9Sc8HwKCYhgN6wiUnrLvO4Llh6AZtiRSD6DaE0UoyYRG/0Hbda7SF7aL7W/CN/T5/me5xgPfm1AiQ+mtPIdwddxVB31eIbvSWy8Sb/2gFtjKpci0EdsUjiH4i/Mg+88Jp9qn8XnEBPxXZ7ZTKiA7bDNWPW8iiKLIqeTajaWiHxlIV3eresRWots3tclV8m+QnHhtVg/bdkgmbXgreO1yC5ztJlgb/8PSmrtwx+HY3MLxWinV4YmGMrU7iSzj7eJVcFqjfwlohCXbZVotWE8zxTbQqc7tlEEZcWzlgS2Suu+GrjwVJR48qUPDhZlfn5HMfl3glUdU5/rq6B2+rru3tITKwi7cKi/Ap2/bDliaf+pJJTa2V+G+ab3fTcpFtOpVO8Cjmo2aPdGY+Bm5oOGKA/gw08qKRi3aou82IkBnnnWbTUTaabs=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
