---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgBrXKu4vvs8Z1Y7B+SUdnF5YZoFPXbjhx91lIIz2HJsNJ0p1gDj0ezgE9eIJyYrA5c+P3pirjY7MenEjZnFj1VJBCm8ltYKrRwy9u6MWdturRyUcCMHCCWrrk4g7nmzIWE7bzHcvBDKCX7zaYUXuDyw5CcC70CkctopBluzKP7BEF0UTOQsuW7WSuLZtEkmy9HA04ZHBE1Uj7PiDDvIwR7r232Eha7uZg0kfokcO/SJR1fC2aP0tS0iyw+rv7HBqxuuLR8RC+4JlYt6cyTuE4i0EXvxzFTpa+O48n4kAue9Qz7VFLzZLEEOGX6o3+kq5ngmrJSBvJtOFFdsRvTPdF5r12nqHx45YqG2zYUNPtxWpUzuTIzUZ6NJKIYpYiCRKxhQ3LtsyGhD+18G6QLkXVj5fn1xnZa5g+akrV9YcaF6oLPOz3Wx+26QU+oyQP1n1xlG7dGUo/CxmH9qeeLjgTuu1IUM57RVX04MgZBKD+CEwaDg8SfpN6331Z9f82KiGeq1sRMz+sa/RAtAmwGJO4G3lYOCVOvD5ZIr0C06j1ruptJ5aYv64QnUTDNWQ/i3rBnkN1KVF65cX9Rl0nmTo7m0ROymwjj/esBsIE8/d+lxummUgeinDWhVJdbK+xSPCSzGWUuaRDVLt74TnLPGiSUC0ffGP79f/9GgAQ10gqsBrEL+kCKZG2Ofk+m19EnGqVC5LMDRFY8BAZAZV4rGk6esU7cNmzDvyRJJnVthuaTAUA1bcAeGJsN2wyDmXf/y0ajInquqU4dj4ZFW0aislGaho6wdP+tAFLkO8EctJ/4BbgM=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
