---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    CLIENT_SECRET: AgCYqv93tUi6u0GV7dy6bLRbDbrEkOywGIDyIPYd5ZqnwbC4ZCT3PdNf5O7A5sUXJIgpXApyYONzeQ4Zx9cbOK1Z/sCxop6eT9dNUZ9GY65Xo7u6lovS03ctof6T7ZSa1HOinyIfg5pE7Kbq8yReixOOUevzN8k9vAETCh9n8uWWMN7t+WcdESLH3zZxaaKo7ytQVfCUc3bVZ8uZtUxyOK02FBtfQkjbwz8RTRykVJv58sVDHI3cmYAgWh0vesv9pK372UmdRU27dn4Nix0d8Azs0bomRpDNJrmIWLL6MrE/Vv9maZFqO4ZqRjvmy+bRP+/jXQIuDuTVRr60W0uLHbc3hwn9ZW+mmkcqheXjp9lwrWj2fZuXd80fbahs+c/z1H/LMLh2B9Amy4JIphDFlcgM7U3J13mdvf3Zdsa9zARZqjlZVh4VF5JlaNZx4pt2xtZUxpEQyMtj46ULnJIQR0REQec//qSHgQ52sr0sIcxhXmoiu/INC2h2+qfMoOVun3UvLynkCwCFg2JKF4w6cJGvibYBjJ+cmCyIc2uE08+2VCSmefGjfLS/+3ThA3Jp0LZcN3oU/C5hi+hTeApgRLuGuGFnd7zAf0+WNangrMgSFB/sl/AkyRL8HZK1MRo/pdziIwk4diROLE+1EgB6OsDu1SLR/Rr4h94ttDZBgGUlrcX60ShOTdXfLu9BlRK5UpvAY9sL5Kyb7vikgKdNdFmnbE1aG1gOyI8+wjtNjLb4QQ==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
