---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    CLIENT_SECRET: AgAWmJIWC3XGc7GT3UIh9UkksMJeK0z4pAVkHiJIcx0Hw42M7p2tUw+2JvchUDx5BgDs5VUmaeHlF+YX/gnYNmQnEhl2Bhk0r8/MdG6nJ5xFa4mxRzmSI/7/OnnjaTw1lIE9fGKMXQESpMUu7OR87yfDrBljqbEW+t7ERHuktw0YQ3xSdj+L0BWosKFgbq+akBcrQTJjU0FzkvhTZbtbFRJed2v+xez1YqfSw62+PUrG29JvQaq6x3kzpojMA4rflqblHITMA+zcJjDcoL21eckrzjRLou1ij05IUCznyVf57gzTS4M7QQBxydQfUynMdlfg388Xu1fh95ZX0Thh/iolkezuFnL050zGnkti3V7RqC7hLFmB6PUEHxhmLU+1MeNJ2eLpxPZPpAA9Jiae5IC9uHUWn6tpevyCIThPqjDAZvEQ3X158CQ/FigfYzhQDZTn1tEVd9odJOcYA+6/GVd4LTbXVjh/d8DDlafrKS+L71HKhxVBqbNn4yy7EWdKEFOL5dny9CPyDoYjHAUZZ5aQlbor3wEQLdncFJobGvlGDU7YPorJgLTNQdKks9XQaDGVO7GF8DLHG9wYbObiUu4LNer2+lJS2/56gVpO/TtzxDU4DxprqNjkK3u+Vl1Hn8yjBMPlVWpR1o5DrwMCGQiN8wqGsPrUZ/rpYVgHEIj0or3BYPNECteEWTqaZiEuqQt14Htb01/rq9/yl3HKRnpToXeaI4koSkz71aDE5BUyyg==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
