---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    CLIENT_SECRET: AgAI8eHmuYiWIYnSxdvpswSguBhaenN7MOULvbJWAZUpM6GN/Y9L7iWyQr0n4HZEBEbnIlpTAinBUPSdSV/gvFHZ1B60neo5NHHN2jN7u93yHyt05XayE4Pi83NXw/62ebQ++sm377RJd/aYgdqhQMTIMNALT+Zn1c+pPTiMKaCi+YGWwisLQsmFJmWZ162+B8UDbbKJ8i6H0C2X1BDEZKpLF6+zFU7/fgC2vVZHXSIyG3GQ+JMsonl3cTo2Ptj7xg9/BgMNqn3YBe3I/VQmifwUtjseg/ckuSbnpXLLKnLYma3pkbW/eaLL8+ol5PqaaUix34tPhjgRFJtXyfwxVdxdF1rGwnSjGrgpCEncyxM4PPlk6krsrVdG1OgzHp70MUCYPDy4L4BUGGGcCvsJbx7Dfy3EWGz+loWSfkIU8jQVvqC2ceP19XvLCVfbAod+b+X6TtiSwCGXpwnmJtgiR3seXXEdsRMuzIsUMVu4JDq+ZfSQq1DAOyXVthRv2aQf7IzErc5kJv7owLHb6IN1TA85oEbxHqsWg/0y0Z67UK7UlTZwqxkoUQZ6lN/S4MR2MOOmJsPlxNLp4LH86+Gbhb5DDOgIS1m9Doiz0s7zNJ1wpr6EXGT5dDzk8ubjv2WYAG86lqLXGj/n8LJOsMJ5iYmrCHU1bi1PovidvHyby50xiKEDuLF++/lT3/pUk/1oiZFw9C3ljwMTpGtoJDzor3vt44iuJckUHeHR1NOsPlOIvQ==
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
