apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supabase-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - supabase-api.{{ .Values.cluster_domain }}
  rules:
    - host: supabase-api.{{ .Values.cluster_domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: supabase-supabase-kong
                port:
                  number: 8000
