---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-mcp-env
  namespace: supabase
spec:
  encryptedData:
    MCP_ACCESS_KEY: AgAyd8kZx7yTAFchtUp9wXfGN/amwv1E37Tvh4BwZL8fysAtOmx8cnSPGlcwQUBuhGE9n8dUKep2XHSOxS4S8gLpe+RLI7RBvWzoc0G6zys3Vp/bWmANfSSEIQAK8ktECwJInORJ9W3XC5UTPlhmAIGHI+2i7zZkYOn4sfVyDEp5p7L94cjoFSEAK5DpRDHhMO6V4kBH/UBlc+aoxwPo/KW7gOwRbd7abm5iEkE9xFyLmh/3LUEmnZVmaWSTnOwwGyifohSXdjToPdktCHWCuou6PAaZnyPXL/PntLDEvWqrduEIuf3Hl2kMtBFUYGTxwstov4yAqW7P238/dmAO/Pmxgk4BLmxkpX8eQVphEJYmhApVPKW5NcW+d7z51uaK8sMJ7ZruJJIP+oqFVG5XB3FLPNO6QGPpTeUFf/8FozQZkjhx0xIJ43Y0CmzRxKDz6AM8po/0JYChbVucCj1yYOrxDZvDCHV0X+E3nIj/1j/a018VfQcDMM+fjLheTlO78Oxbb8fvDv3x092mxjLfDdH1QFVqXAkrrDMVyMyVdi2gNIMbjB78qPsin8fDSQjKzVnFKWiprVe7XnaFKrSesl2VJsBGrY/CBaGIusLZHjjVyuNJZox27i2sJqYsABaXQS6Feyr+O51/BqfQVwZmOmPV3d7jvA7gRGCfQw2tHYckzN4nBGFd1Wc8RiGzs9zgWoPAZxqJfPI+fBkIcSLAhbi/M1VXlHRdBSWcZ+ScTyV/oLgAGErkVDXHpiABsQORWy2KVAUKCStYDko5I1+Vj8JD
  template:
    metadata:
      name: supabase-mcp-env
      namespace: supabase
