---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-mcp-env
  namespace: supabase
spec:
  encryptedData:
    MCP_ACCESS_KEY: AgCD1vKBuokStC3oH/rvaQR2Vmg6m1k3UZitWiY82fUCtDc0mVDIoGegRZUtCSGgHpB5wxuXD3ZwjjWAINQWe7c+fcvCZaaaKmL3nXrFszqlu1bGSqdkaAVe0BM/7h71GEs1bPhUBD0yyC43FpovzE1gRM9YBYOLn+4qcdw9vP1Ymj88tzYdkP5gxDHlahsopBiw+CvRdOIXEdKY0txcG2c6HOGAld1n9i9KLY03EU1nVY3GeBuWePvyMiJTODJUEqEy7qteUfQA6Nbm/E1Cz561WGhh223UPpaQjfF2D+dz22Hrgkw6Rb14LX6D9hZXZiFVFFar69HYvNquIllWNTA1jydpLDDaQSYiRrcEwWCd6SBmewjVaHneiCrqarqmekLm7fKl8isCnobcwQMGeJQUKoM85utbCmoQoY/v5KXt68j1AtEBIbG9hPLzZDXZjDyCb6sDXI+ogJ1IKYRkf/Sx4ixxl6XSOh2+++b6OktvPN9Tq2d4fOQLk9ztuXr7r5RV5xop8gd7DcX0kXLYnoc79h0WJmkffpEb8rAbN+Bje1G5XB2rUS9sUg1nIuQydfmiRD12RA07ppOuDfvsGt8oR7s8XrpzIbkU+YeCMPfj0pVdPkxhJXeCZ+q8KK+FgCwJiJO05RaWyViq41Vmw/s2CzwsoMArlHW3wxXq+HeQiV3NO6+LmMk9maauzPpTxzNghjfKDZsFeo3Be6mRg9BujgM1TOIPVJoMJ+0qr3/pWQ==
  template:
    metadata:
      name: supabase-mcp-env
      namespace: supabase
