---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-mcp-env
  namespace: supabase
spec:
  encryptedData:
    MCP_ACCESS_KEY: AgDITjAk1w/dM9Osu2KobAhuNJyILsAEf6b2TnXDW8gku8SifbjdW/+PubZCQmTqOL7CFWav80aM4nPSiv9wZitoCwEB+jn5lTYXTvkzlrSg0sYLZz7keBoavVhw8yHSWtk4GmOGYXrQ8TS+TB5nRBSYtEr5yLHC4f1g3efsSFXBy8jBXEl7g4SxdFYfH7l1qfwdi9+/EQmIYtwRu2Xx8GoEOsDpTUA/25iDnbsaNacFLext71oFFyhvWfb9g3c3w/VxaaP5gjUhe9SGDdoJhIaeJeQSZKWhXL/u0IH9cCQEZ+WA5rfWfcI3qIPtlt1RiAbzeoJSWSJ/z7dt/q7szcpAbNVOZYY/QsKzLwergJq3W3jpQEFq/V8wyNhXszZqI3ypNSzh/+ylWM6QufzBOhhQkNtT50bCp0kgk1jwQT2Sew+zeRfgjs/xfuy+B8WEM6rRgY0/vjM15ALoD1j7Az10oPlEdkwp5jNpw53FRUZGwwUpwDdNhRmDIVYnZ95mKwLBO4dumJWC+auxTajAqzG5s7lyhlQ69Fv5oWaYD6dEXVm0zy/KhsWtWZ9cjZ4dEwfy1qqMPfSAivCTawjHDclalIx4Jp3EtNe/OrVDyLKD6hPX7MjN2H1BImcabZXriTy5ySJoI4h9XnLaYL4uMxs6+UUO4KRsCUzzuvTRzORZLxE4Yx/X7RCZnkf3NQftSndVa4YbRsjloJmygf17gOkXX4w2DlZPmHUnScaNcxkVNX1zWEVV4DjIQfpzXLiQe5R9X52hIzhiZTrDmlJ8UcI9
  template:
    metadata:
      name: supabase-mcp-env
      namespace: supabase
