apiVersion: v1
kind: PersistentVolume
metadata:
  name: supabase-db-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: "{{ .Values.nfs.server }}"
    path: "{{ .Values.nfs.path }}"
  mountOptions:
    - vers=4.1
    - hard
