apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-db-data
  namespace: supabase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: supabase-db-nfs
  resources:
    requests:
      storage: 50Gi
