apiVersion: policies.kyverno.io/v1
kind: NamespacedMutatingPolicy
metadata:
  name: force-amd64-scheduling
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  evaluation:
    admission:
      enabled: true
    mutateExisting:
      enabled: false
  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
  matchConditions:
    - name: uses-amd64-only-image
      expression: >-
        [
          "ghcr.io/diamondlightsource/blueapi",
          "ghcr.io/diamondlightsource/numtracker",
          "ghcr.io/epics-containers/epics-gateways-runtime"
        ].exists(repo,
          object.spec.containers.exists(container,
            container.image == repo ||
            container.image.startsWith(repo + ":") ||
            container.image.startsWith(repo + "@")
          ) ||
          object.spec.?initContainers.orValue([]).exists(container,
            container.image == repo ||
            container.image.startsWith(repo + ":") ||
            container.image.startsWith(repo + "@")
          )
        ) ||
        object.spec.containers.exists(container,
          container.image.startsWith("ghcr.io/epics-containers/ioc-")
        ) ||
        object.spec.?initContainers.orValue([]).exists(container,
          container.image.startsWith("ghcr.io/epics-containers/ioc-")
        )
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          has(object.spec.nodeSelector) ?
          [
            JSONPatch{
              op: "add",
              path: "/spec/nodeSelector/kubernetes.io~1arch",
              value: "amd64"
            }
          ] :
          [
            JSONPatch{
              op: "add",
              path: "/spec/nodeSelector",
              value: {"kubernetes.io/arch": "amd64"}
            }
          ]
