---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCagtm6pBRPkBlVuJSXGIatihpnH1wLKjMVq0inIIyo5SX4v0S/Mn9gKQUEdvinp4h69GXjitP5h3apZ+GjcZ4hjrlDXnlKbTL89qTmM0xDdJHyHe2kMzCjuGX5OZsLVXa5ACLhDM/1kuOh4mvRYxAzMnLmJekG1/T+k2rg681wSdEYU9UdhpB95sR+YzUNW22VJf0C6tDxorabHpA9ShTTZ7z9McDeHQ3iucCvimwbujnB7b3EYXcX2t1I6DH3aIb4I08L5R+3z7r1ExXrqtH7BbqqqD23se5054oQIEQq2qoPNh98+X+nFn/GRMYji9ARtmk86pE2s4Ug/78yKoIBbhgMbnN1/aOVTz0FB4+4ZhgjPWpANxIjxHUvT9Vrz9Q0YWRsdCKwbGS71KT+jljn8hGblIogd2XP33MLscvLSG7ko6L1HlGZrG3WsNQbVwzjbgq0CS1m4QNaM++rAP7lcJG2bzu7oR45yEXvI0a9/LybYk5nXG++7rWEQ7lU8x5uZuk9artnhDanpM2zlW/Xvgl/uPhRIyEbrX7SXMKmgflL9j9yjcxeUcv8G4cAoAfkELgi1wy3ROWR8Af/ThMbXs5ylvflE+fFbWE2ktJBpnDVDY0N8N+VgtjUiiOH3TXb/64jmd9UvAoCBqIM9s7mufdjOS/WlYATLblm+5UbEIGP+ss17kZC7gBuWvVmUetSwqPHQq4WEfWoJipxQ0cBK7/IZnsr05XOCjrRxMrLZ67/EJD2VyCv
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
