---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCU4rw/a7AINtIjWB9746mFXBhcwsIME1vqhyX8BjGYAEq7dqHACpUsSlI+UpO7hNiOYyvHZd9Mk9uWI8jDLNACMTf0aTVbpR4joC5cYWXngZBmMd3p95k3X9AO9xWKBmdgaraXwAN0lwbwHR7OSTmZZM+QLcDkrZIjyNA+SmL02UnK4ZYvzYJtan4k2V8tDyg3cY0sNCLhpH+zraPOe68RpMoiXdP2Nx4igOgQ+nzojGZulBsBz1zqjUufmv6kqbbkkZw9SPDByNnicLaJiZkHAWRLY2gwNMTbXL/dtm4osA5sD46Ks69NgijJCToPL8FCFFj2vIWBQiRvxY2axNGuyYDxiYPlbL/UpqA40rsDP6bi/wdrQyLT1f+8f3uIOoHTgwl9tzJ4ImIkn/VzEvzAuseISReoRnIsYAE3iNMJzLkESc9RVxm09BaWy3iFd05U1NO5On7wBTrICI4ULI4hSMRad2DU304qktvOaj9RC0QX62ulygU8DBdc8Y3QQ8MD0TgO3PE2vM+3VicVSu0HrG+kl5PjIcG6i23XZe2X54oRv/xSaiKv4NEB+QNJe8AmCj0Py/DjDYm5D2HyYAZnwWCWnvOwQtnYFhxSehOfvZUZL1/qAJNLM3waFxj0akxnaUhSH/LWcDizG9ANnmpPEYYNl6kwhPSdEdM3sgCXtOQZpbJPmvPrW3yCqmg6WV5WJmGE6mMC3qmLPwsYJg/4PWWY04SvWCrRbz2v2S6Lhqh9tyWvD8Fx
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
