---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAlzaax479HH0Qy4WtkMMMSweelPt/4Al9CLNFX6WMspaALPReU+9wH5a9sOWwZs8VBkzB9WiNxtYPFsV6GpG/0ULN01fI/dfrVfQgLvt0zHfQ+G5/y4flaWUaTtCK/xJtIlbox+rLxc3+th3p0+hE3Hn/MAmk7QoiFPUJssg82JLP1Gk7en8PFNIWiUeQ8l93ego/lYNA0cNk7q4eE4JcGKgB1ohVHUlfSXdGYFX4jq9wxAbTae751e12R7rsRoLQHXf+Sr5+eE5blRK/Lx2PdzVyqCc7sDR5UDmZvEMle5S+OtjoESIS0XhvPthNf+fde2kZELGmUA8uh4idXBjnv02FjnjWaogCVKu8lVEpnWKO7ZG/E5WXva/0YZYK1eKfO/10Y+yUTQYp0rC0QArD8TifSWSH/sD+oKNwfY8G/kWV0+BognBa9fjef7/Hgxlv3ixxW7gM25jrVZGwkxGrwc3ZIV/NA/g0Id62km1fZAs/StkjpSr+CS7BgiLrRb9n++3da4zfeL70faS4jIXfylDKjvLAA0s7omUqBMfkkHGclpmlyQ6Tu1JrZP1q0DOOwr0kMVskQcGW0tns9Mf6CCk4uw3Usw03ROVRKZD3xCUVDKTUxxD6rdADKx3Z5yEYg8XK189zfpoUq7wrlmfcKCEFgLIPnyceYCkE0E5k0xuUK53ZalaSXgLABK4ble+AW48jZF7AH9rnnCcGXLUOwxow6wTIME3Mq39velSb23Rc52Ul3Ojg8
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
