---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-credentials
  namespace: argo-cd
spec:
  encryptedData:
    dex.github.clientID: AgDEB4eZp2zQ6N/ws8bNq85ywzdp86pf7TH5doz0Zehx0JJGrbRphA/RItMg+ePLk8Qp3nSiMPymiOiiolk04WyTxD8Q4UtAVDdUem8NK/QMIxiGi2sYewV5in5FJ86p+LUmd9KFQlY3gxs7IJw/U1DOZwm/AI7TMRDp05oP3weX7tSWpp1h2nsXAt4X/YYbgYUzX6ECwnWspJP6W9mvf7LT/C/+rjMSb5Td31iyVpzhlyYz5LFHzXq0sPBEXNxs2duhXNHTFSNKyPvZXy1Lw7LsnQ090z2oc60hPus2J0EeTwfYQtL+h7NbvvVfUahwhPc/vabZxpVRZQZdFVlzhvmmfMzTCB9XFMkQD55YwL20r5ApIcwUhDaHr5B42vnllR1Lbqm5UgBw0/56X3RQpfxRkDjZRvGtPVWzSYe5P6NdxABSut0RRswCG+Rb4WaIiwNa535DX0oaETiyT9QikIbXBqLnHq1/fjVpJaZkIdaeJonMGpOTyRx7fRVzfCDc5IQsY4zWjWQCjhGMbYEGudS9ypsCDMqxo5NSzXOvsvGZgKFXu3FZhjmaOq/HKCXdfXU+WLRUBlTlsu27hhueDbrR1k9L7byhOFEn/uUsXkoSrdZJz25jZ1yIDsosVfDAE9JjSIMKYac8d9VvBCBQnEarfLqaANbx1hDSDfjaUOsNiePXx9rhAHodgEebi0JIi3Az5Vl1zP80Xb3XT88aESFnW/Z1+w==
    dex.github.clientSecret: AgAU13RgzbT8Z4/3swtrZwuQj86R2p3Z17yr8bUOkagJ/Nboulq9WOj007+Cgp8/9E0L4qB0e7qS5bEWBhksR+Bz7YqAl67wLeQC/POasNGhbVAbx5tPZQ3wUgXk3X1XqReamce5rqUWRcBFt3npKAwGFmQrCUFy+PY12j/5Mz1kV5VE7smzGBd//M+/0FOWyORnrY+d1lF5E2I+wyQtf6RBncWg2C2Xl//es2FjC5p8ZJzeOZ41ssnLZ+2EhzTfAG1z/YC610wkXREwAjq1GLrQrmXLj6E6s5mTRvtn719i+bAiJy5W19Tkiq5nop+QelDHsRnzJljsOqTr08+Z9D9ezO2Kl7AiAgQJfaPXX9GEcA/rXM7b3+n8ZhwmhQKg5dAEJhcQMuIYwo1tr9+WEaOD6NFHqlX77kJ9lwO/yqv6STFtYhRKgqqQ2+mdVRi/8Lde7G550MgoYRiUMZ/p1khTNbT7FrihxaYttxPFNyuimfe2JTKQtnWD2b86DoN24FPkaa3uGDVIgglK06rSH1RbLcgEClzLp0IfqHVqITOuAwl/sKiISqQvI9Npv6y895av/cpyax4STP3H/CDj7kUK8a8UPMtnUcQ+Ssuk3BxpAp6mlad1j8Wv5gmNUXkVX0EWyCeZ+6VsntThZcM4ucWHh4bR5KE+ENn4vLqNo3dSkAQVD99pqFvCKbJdS4xEJLQMYRjLs4JdoPcZMAcKRN6tBHiECfG5mUo8WfTh0S3K3b3/c6Edib62
  template:
    metadata:
      name: argocd-dex-credentials
      namespace: argo-cd
