---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argo-cd
spec:
  encryptedData:
    dex.github.clientID: AgAWYKu95YFNMVIsa7vTlBW92CPX4aSuvQ9uYHnsri4m92OYpVv4Tq97++e8yLmA12WoveJ3E/Duv0vZW97/ezNVAKOOFgX4zQwOJEfNFH78fs/e0VSaHDQ00YAWJZq6aYPQzfrJ4gS2qnDiUs3Js1A9JBG0iS3t7lUjzIzZ6I6x7/8oQfN/mp5VEar4Xk7h1tFV/FcwCIpQdQbOUvc0jFYK65oIkVsrP9atmbXEKgn0CI1gcm17yram4oJQM2/CJTl/PXTLBeSa1gdMQnL3MpoB2OOjMf2KCNIK51DsHDg8JqguBxzeYknsdyQplQI7OAEGAvrUcPuT8kfvObE20Y+np7gNEiYeTB2zua4NF1y86gSsI1yKg6qajFu2mo8/mjcHwpiciOLuOrvytBavlTBSaaixt+xHtl6SxuEI0Ew0XHyHOEqBf4jWySxMz/DOcjdPXN1Kwq/Wn94X1USC0iuTjVRgkPqsJerR6EUEucKHre2b7BtwTEdUfr502fLVDMgrxK+74NXzaYWWDfq7/PKRDWtrTXa6ygwtN96IOE7dDWV2JMpne6Pmcz0la12Te0FK86rIKDBEHFsbggMEMgZR43vD/tPRvQaE6gmrkCWLr+Xu4Q9d38Jo3dm2yRgZYK9h3rS6tK3iTT3nXU4VvIAWlWDLydKCK0W13wBWHOPgr3DZNYlhjunHRO4lTSufvAoM0FISEbIi8vqHQWEjCWUM4kw7mg==
    dex.github.clientSecret: AgByImDZRpfDxVzRFT1YdYv5+3Kd6XxGHfX8gRcIY8UKm7bGVbKdy4vfD2c02JY6K0A7D8tR5+xcoxlh6GRbRXFXc0NnvB/U8ABi5fs8N2xPvyu0bB3PYGjymaCtcElNkjxbi4gQiei603YwkFpsln/823oSdkH/1oFjgOcRr/MrjqvZfk3eavA02L7bdNKzIML37GxvM/QmpVa6zuSbHqMdEC+Z3wfHc544SyAXTMLQIwyzRN0k2ve52aT3gPKDiFoc1mnx+b2p853fp5/2ywIGatmx7H7HnFHe81QgLM0AoePdmNolaYY+PV2BZcaNkqllqwZBahi0BWoiyfp+hM99oTXzYE6P9mzDEsP2GwqxI8My6DRlmCsw20ii2+jbxPj3hq1ejvKfB9FI8d+f7T6zMJ7hZEovBELnB0F76DPHantwmARZwPG+EeEisPCmyFBObTzywlO4tHLU4JjfMImJSuKZQYiNWeBqHwerkhOesU00CttSjrdBjEixRC/oe4LIARo5YBG9omG9jAPsJbWm83yxB4kEpDH6kHKLMz91Qzh5hYAw9af0BqKwghFwtIDhjbDVK65mI6vhAportM4/8olB6ySD7bJTkHliFvng8KswsDQMj9+FIDZEWmdC+IaZzUzhtuWPh7Rg2P2CfYLAOkyknnKSVQ7MLLqMK8PMHwvmJvY8BmD/awgtWxbJP7AcSG5SnXJmEVhp/APbRxJvRHG5XkDoCl+nlqgOC+ayYHO3dbRPuXnb
  template:
    metadata:
      name: argocd-secret
      namespace: argo-cd
