apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  scopes: '[email]'
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, applications, update/*, */*, allow
    p, role:admin, applications, delete/*, */*, allow
    p, role:admin, logs, get, */*, allow
    p, role:admin, exec, create, */*, allow
    p, role:readonly, logs, get, */*, allow
    g, giles.knap@diamond.ac.uk, role:admin
