---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-credentials
  namespace: argo-cd
spec:
  encryptedData:
    dex.github.clientID: AgB7XDTKF9ufnzU4IEyWbWEfCk67iEuxo2Cxt9N/oCx1SzoDpvy8RH9C/AFO+D09NNGnMPH2wsb18ogUYfMLFsMFd4MRIsNfWL1gENicU73QK/roPdgT5RqBv/gyKeJIMQxoIaiJCtr9MSlijr5J2Fu9BU7Ivs+x922K3/ydoZ97k4B3Ay9obW/ji3ArlMgvoQI5gve/27K6NUxlouOsENGNhelbTqTJY5uyC+GNpyvhsPZUBpFEd0nmVOkLjyqHyuoMR8oyOgWpIL0f9ddWsUjmjbPzGTwn4tSExjyNQQ4CtM18rhqYfQDy100AIaaJi2gvrWU9MKBgq8Cf6TM2LSKgGna3OQ43UBUYWnOueCY6XxyzNLNU0tcc00N27XD4C8DSOe1Wg4P2YHJarr2lfsrlWYDcn9AYQTTpIovbEbj/9Hlut/NxLpLsXQWi4zYLTc8CkFzggbdBP6mk874gMleSw6GQ5WqrVyKe1PxnxxDYPieO8OmRRJ+BwcCcSPVqNsiXh7FKakNxmfJZFYh3E1b7y8xoMQGoRnuUnM4xnwZwT7MD244hD1mm7ZHqFceWJlzOVYg0nO0BGxyCX/ow+MW+x0ExlVMKIu08bxnfDzSQJJr9GFJuPTWtNTvj3ruv5sYDL7HOnRVZIjOC4DY0lqFf6uZe3PErhI1dbEDBtHu7W/WKK9rrNpJiLWga5IyOL8tr5zTzunBOfDAfengGO80FDRSKbA==
    dex.github.clientSecret: AgCZdoG6KrC+/teY5PnHmlpbaXzLxEh0G6u0Kte1Pqp8kZQIyfkk4gCC63Rrn9YcN47ssIvhZoHTKJrArwqK2kBST/beCWnvliJIRtVxxxBLCf//cY/z+uj/DmCTaDsfyVlWBLBUKj+yvsW8wkcCaRmJuSa7w+N/J3+8qnX/fz70BsLJR1uZijLP6WIHtDYJ3u1xMYkk8aTxB6wLIsYlHoGgUxBAkVgRuvXpE4jeAIinefg9Ul96Dw51Qd2X5ugMZiYiz3p6tqcSFQz/eXK/fT026BNKDc4yo6OOJ+oaZNK3sYPWWXu6mvw2axYmF73t0orjMgDjalpgJ4GI9Zr2pdpsYhgoofBGjMQiPQuq0P46eK4luafbF6dpoGwhYnpfHRFuLIfTvipqOrCKVhVLcuroqJCFQGyKj/4zU7YTJ+GaNIx6vo8c+YUfXRPv9OXV94Aagvvmm9iLo9/A2XduGjO7cTndNZmi0jvt9vCh6Y9FpGr144GfT+EXhC52lby8hIsaMTCYaAUy9fOumxDFb3k9/5BK8R1UkB1IBbhMe/a2bhGRruvAV1Y7QPUTBeGLG7FMPAhMFtjivgIFppXglufNoG8qWugjmDKwP0xoqAGs857vSrkXey1Hdx2vFdzlRqUGCKxg5ZRtd1uwRe9R5q/JezZ22ka2ELC9Fr0KzOZSwRezUd6MH8qI5ytd2Bh1f/QqWrikf26nzukJ7ENHYLiHHgn/dkG3jJEc4MbCvYHbEp310ICzsZgq
  template:
    metadata:
      name: argocd-dex-credentials
      namespace: argo-cd
