# Install the control plane for k3s

- name: Remove k3s control plane if k3s_force=true
  ansible.builtin.command:
    cmd: k3s-uninstall.sh
    removes: /usr/local/bin/k3s-uninstall.sh
  when: k3s_force

- name: Install k3s control plane version {{ k3s_version | default('latest') }}
  ansible.builtin.shell:
    cmd: >
      INSTALL_K3S_VERSION="{{ k3s_version | default('') }}"
      INSTALL_K3S_EXEC="server --disable=traefik --cluster-init"
      /usr/local/bin/k3s-install.sh
    creates: /var/lib/rancher/k3s/server/node-token
  when: is_control_plane
  register: k3s_installed

- name: Set the k3s_install_occurred fact
  ansible.builtin.set_fact: # noqa no-handler
    k3s_install_occurred: true
  when: k3s_installed.changed
  changed_when: false
