---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oauth-secret
  namespace: open-webui
spec:
  encryptedData:
    client-secret: AgDTOJRhoRizsnraTL611Z+kWrauqJbPf+icWSclr6yG88nb5N7qmfVxUK4RBEsz2TN1KwnVyBZV9Mxjl/gW+theOeTh6olQN71A8U6rBMDl/B69JYOhZ0zQntzjfji+0FT7IlVHa28XF4KgX5as50OfPRqCNteFNkNCGb1DoT9t0bHN2PjPc60eNGv+vnRYPjBHRKBLeTRsUChQZ6LxSqkEKpqXa2ACHRwEC2yb97L0qY6MlBplRBxeo7JM7lWFZV4jVI7Z216Za51uXFOCj3VW2FZ1e/X30yRXqifghreXEpa+gduARacB4DIA0nGCrixUO11Ijc/E0pRiLqV2Cz6dSfWhWipQa0uFREB3ma4SRDlildwrxLoRBiR1Kl5fxznhJ6JLtUg53xn1BhRTSusaWyOg4XffhbsSFzVVg5mCueUOvz/w77hPxR8q7t5o8VLi2ECn+mlLMTVmlg/g4G2NpfNDryRj9RsNECZFdF/miWzeJEl0CGo/kZPpRrWX1LUpJd7JRBamGs2Zcq0Dzt/MckW0nWLJQuS9sMQ6PR/Urm7pJVjkJbqllztK0gAjGM7bpsqJj+36iu9hz6CF9cTHV8WRn0ZnnjDHMK14wk2rRv5LcAUYSpvGC8DPXm3EzfhFtr8yoTzGmPnN6B0wjqlsl0ySxX/IpAzXOQXo5okW+sitHYhhljKmxY4k1sktFGCvyLTcngGQdCvxqfvmeYPOG9GnxPwM14eVhke+OVQnFA==
  template:
    metadata:
      name: open-webui-oauth-secret
      namespace: open-webui
