---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oauth-secret
  namespace: open-webui
spec:
  encryptedData:
    client-secret: AgCH7MG3bLfr1AdgXz+eORZecmJPYJ1ilgp8B2Jn8oQMOn474DmRrn2M2iwoeQ1Qb1WKSmMIDiMBx2XX3HBAnzwGvfFpPD0z1xfebgrNH1EGUGyDoLdgoFrevaGxmzS525nJm38Sz1yt+KIPsZ2MPS3EGMkMbR4H5/QQa8haIfFHDOhqrMX6cKVZAiJBWeDeoO7NOTLghlF/S8As3knFh2J90hMrz/71hQq1AXk2+cRGflzJxaFJ0iou8enTSbbzidNCdREOwog6/wjtXeK6BLAPD+nKO9hkoFfsQN26GkHXMw8uvIZ/uS6uSUlZ3An2U90uGyDBRDi0Jmr/m1EIlToa2LjQ0EdQpAcJRDMRtzIYjkoDcnaeQMfjwVB4hmNFPxUHsdOKdPpUs08o0Yb345a9WTErDwYRO25RjFCv3CbSVq9aSDwAG4U9j6n//StKAfMrAov6tl5+vjR3d9HorDGJI1/ZzXtqyw/N0J6sfq4DJMiJEZ40npeGYXl/jWGFsFK69/0/3X8k9DkywIU+pD/Eq0dbxQKzCf+6S7j96RJZXajLM4fPRknVqPyclA6pmeZjCRD0T8JqQ5q/Acwq6QIuPUenrXvYbKtyneAsUIjZYCZGv0thAt0aFUkTN2DF9crEYmDvJvjP6ygBHTcHT46O/CWv1Y8G2Vzl8U6EIjuj9uTG0PwzsLLfrMRAAGr+nfEPYYpfs/5stXqKSfXp4It3hNF6UUTOnTKP/U8fA2EHfw==
  template:
    metadata:
      name: open-webui-oauth-secret
      namespace: open-webui
