---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-oauth-secret
  namespace: open-webui
spec:
  encryptedData:
    client-secret: AgA5DQEZCtBPrrO/R8Bz+sORmqX0fhjMNaD8V7tajuH/snjnodGd7byRC0Hjzh3wmFU+bvHhlXhPcsQtQGzNv6nBxvGBCL0m4SwPnuPqCegvZEg0HgDLK3y60Zhd084QrVCbG6Rk4eK/n9xs1ApSpsXd8EiHwdt8zWzJPvUJ/CXXTMRuawLL1nI423dzxH+akn9n6ViQtUSNKxVWU8Dl7uRL5TpqgFdgOx45INiT+yH5aN1Gc+YBz9xZgrvcaMT37grna4ELkecyTHbXcH6Xs2ioenqY/AW0tXqx0Qs8FcvVoE6GV0c1FJmN4wmCkyKSSeBaSaRa7B5NOyWDFyM6yuvvLwmJj5H2mhaf81GiSpuOe4JqtMhlAxTQIB5Rvixpev/QSv/ZISFZ0rfqUGWccAFBzf105+U9X3WgXP6LFWmWYXg6+CA3YPxsixj00IkrnYUQXjtrLu1xTQL+5p9eFV7D20CCi801VrpNnQF+DCGnBW9rvmMyUA+N62ViBsF2gfdotwCfY8vbWCccieSCAb5UstkAUOKP9PWWXUkXIdXOigkqGvcff6UeWMKDUxDE29kAvg0f7110jLm/maBxlRCt+x21DrqxXil6uxLaH1oCQ5qX3k8Pv1mLJMCmQ4PeXzyCDlEgPtTtJsSsJvMMh0DYGtz1vREJNBaXwaFSz2GrlwJeRvmRE+5rvX5qPYvqa+X+kkTkxoUgB0MujPoQvhZEGzOEDYLFowao8sMJnfZY8w==
  template:
    metadata:
      name: open-webui-oauth-secret
      namespace: open-webui
