---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgA156p0buYFAXdpp8NqELGQuDKjnXrXVP81DpHCWafhn06hVWoAjYQSjFsL6168gyiIREhbZK1dCWQsCmlQovbt/du2yISdQFPmf8IlpF/NfG9wZPBN9XXZhGClRNLa/GAED38KjX5Z4A5hrUqvF5TBtuCcO+Xn6BqOfZP5xilEY3rEJnylDV5L+Qck9wTXadhRGKiUTzB2VB597P9/YFLr6St608wINZZ1JUD1KHQ47PmdeZhIgwmHpWlgcDSmAITY4c9CqPZsQPjvmYo30wvQJxQo9BInRqS5dzlTdsdA76hlZfOWLyeTOtgmR7ykWNBIZ5UoBhPcAwJFNPbsa+dcesBUaCTYfiIyKm8qOCQR8qnV3GWRajDMw8nESUJ2xm6c3q1ydcZhvwOcVo7MtpDG7MMsQ/LoAOn4/6O33LEu6bTQMc4xQNkYQAmI79Kd+g/ZKKLqeZTs+Hf169ysXiIoC16aOFd2H/yr0Z9bDhh/iTMbZwkJzqA5BTfWO+GsnpZmkgEjz5n92swPVFaiRV2eb/nSYcJMpSwNucC8nJpt+DE9tt4Zm4ZKM3kJ6CGzi/H4j3Ve5S9U6bj3CUJE+BUYQmccSdweERhdny2UxCrRpkAlOqhDQgtmdxqyz4tlkole5osRA4Aty3d18/bwpaCCdWMC1XSS6tDCMSesBB3ZUt6QmvVHvx1K6nQ1mJBBi3UgwPbsiJhek1fwWxp1xSQnfhhLSOE1pkigLVKpLp1Cerguuwjc/Rve9h+05xkm9rxGzvLJwgb6ttVuV+w6MJKZY5PrY/u0jDYUgrR9Kc0tpX8A7tXhq1KSRkUneLEZ13e2vNKSKIgkF/5ms/W2CaRXjJSZGN4KsnY9uJSRJYy0kdTGEs0i/8p1RzLoQExPu8BwoBTIbxZqAem39TLfxnwFKeTjxQH+uq6jkOVWnmr3yiBZW4aO9RdE
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
