---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgB5Zw4vNvGfJrVtlpkJfOToMRarufdBlYPBrP4s1B/G8kff0l/MQKKt+80/599RTt/caUA2RWmhqcwHLUktZw1LTzbN2K7NPWmIioPGsuxRwRXteNW2TKaRRDVZ/vHdUoETqXATh5iG8sHIYDxgllRzJB4Jt0dUHc1h/K2gC65LEZslXrMtqjhI3Ry9nXxRSH7l+4sx3/9xCfboQKUM1a5hqd5oRHkq7pwswnLgJNgfmxf4zbte7xlvmtJG97+nw6BqQ53ISuguv1yZ/nY0Kmug/rPxcneQLmD27tFuXAFk3yxxfTmDyqshHC48sqMNyRTb7nIm3WvmtWZImxVvLlPZRyBhGbRGu59uS4u1lF9+ITyt8vycpbunncRkpZoXwReqPdPzpc1ii+Va/ghKsr0AS7ZlrE9jVcTd/NcHoxK6dHg17e+wL7Z3Qg4Wm7SRsUIQHTg7C/SrWlxIZ/vniwVsyftudIFiawusQQtU5a6s18MPH/Cj23pWwx9ux04Py6JmVPfZ8+ubE+7vt6uJIDy3XBdvCECFO7kUjQVg/fuWDTisHyrOrjNV5ZLf/eO/vX7aMJG/IARrlNzvAjEdeN7sfDvxgsuUZLPlMwM4P4NKJs0dp/pYWIrGJxYRxqG+/vph0K8h7LpWpJbxPrWXxujCasMynRf9/Os5CQ913dA0hRwhHs3XCW1jMsbO6VUn/tazpWTm5WfJmwrh4d+K4oLfvF7YGGb+9IoyVCVA2k+lF8M6PlaI5ChyCdXRx4o2ODfWxyo4ZdWv1XXE/8WToGtiS4e0uTufC6VJb3861Ynz/n2uaN4dQynM+y86ddfMeFsVgmHz9Sbqjn6EV07Wu0ElZsj2j7AE/TEvtFM58T5nPoaDp2lbb/qopONkhCXLpt747HqLPechNoXKe18k0MgcMMD+6Qzj7AgPBpw/pXGYfT/191kFYuvs
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
