---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-monitor-oauth
  namespace: argocd-monitor
spec:
  encryptedData:
    client-secret: AgBBwFy2mqBSp2gPqbQwGi0tnWd9cv7gsyzgj3DcN/2rFjMkdcmxaR/d2k9T2qXIwBJlWBFAZh2EDywkQfPCRvPqJ72AndtBfvDl7mPh3ea09/HgKVGMHz28a2vfl8t8jW837k9qvti6HoDwx4LHhEV5pbGXXO3jGlOn7S9WXkrsXVBk1ClbLvSUwK0mu6K0t2RmNgTylST1ZfNLMyXFy2uE3AmkyFjp0Mf91F93dVx3i4TcZu7hO/FQDx4lCk3w6b+MRGJ+qIRGWrYaI6+LdN78OepauG1IBt5hl9Dmg7OTq5m2p4z/y8fPbx/t2TapluSpYXXLoemNBzli3oLxan0SvnsYCbVXpMDJkkWbLcXvfhZWzFliC0YN77eFYGGg94P4Ly/3lwZGq/NWDKmXw9FMygD5rNg3TAdI3bVsn/l5HLYlglWr8Vy/7UweMhFbmxX6ZMjXMONY0J9TswstwzE8LwHRQ1w6kxUXITPyEfF1J8Ybv8WnlusmTyA1Ua+4kN4uoFUt/3497GEf7Lzot2aXYMKX7QcOOtIkgpLTP3AspXQZAFEHZW3D/3L1M4DFIWz9IHYwVuvTjgJ0ijh+iV5edG6/pl7vkUp42QdWwKwtX1Mg2/KaE0OKqJ1j2woYZ/pK8pCcPd4Rk4vfbYwaiiBCT+C/L6DYaLmt4Bj615sghSic5LS5LziMyDeoiBTPYykswhsXB0dRWOlpVoS9PFw8UXkaEI5SUlZdv/sOc2HbxA==
    cookie-secret: AgAU3HHxFqxprp37vx3KEeXshzx+rplB+LRk64Sz6fAZpBihV+iWL6e0HrXesjjvgJX1BHrk+MfNfKPyukf9q1MToU/CgO4DefI1lwPXG/2l+QXrowavxserw5hyCTIrwcQm1R+qTV6+sRBeQiD6Uy1qALHpjgsCo/Ie/s2/8KEsWLSOs6ieKwduNWEQ9qktC/aL1GXQXjLiASDFo+OZ7/UUad2PVOTAvXtC2317FW6BlNiQlr3U4r0Me9X1sKZjeh1713XBUC/P0oM5jTCnw+X2URRGxcZNPS538nDOr7pfkIyX5XyX2V+DFW0h5AAvpePMEykW0e9hnKZU9WVsk+ZlgMPFBNzer6ODM+3jvlb+h69gL8jrvipyeUxVyPLbu6KEgtDmV7Q2NmlKeSS5t5KVo6lQUjj5WBjs/p9WwRtcQ689nO3Hvzd7xXuYIeoURxM8RnYbOz76ozXtD8UYOGWfgxfK+BbiCxGg4Lcl5A/TUVqggpvdyvGOZxPsZhFumPQNoYrj/7QpJSBQbFHiJstLoMovwBd83C+MtjWhyYOpT+ChRpURu0HrIC1mvRcm7YVtMjiboysqN9eNisNOKRdS5dJ5fRy4k3C9T4LSrELuh6aUbewYVZefDRjlU78rKiUvIYton+2lUhIcLI4Xew4JlrgPh9ck8LaGh7cwLuvOX3DGVx3Qi6h4KQFAqJd0r4AtVsAhbq5ml3zmrRnN/tFg38qBHGd57MMCaOUZTYe8fA==
  template:
    metadata:
      name: argocd-monitor-oauth
      namespace: argocd-monitor
