---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-monitor-oauth
  namespace: argocd-monitor
spec:
  encryptedData:
    client-secret: AgAgkNT7yLai1t7XMIm9hTxHtzdeWzZEXCjYaXYHdXDrowLAkNbedVZGSQ+Ji30bslxkftE+bDYOaNNBIa5UHtv/POTHbxP5LeCAuFozHd4h8Qc9EwpCbFDx6U2iKoMO4r6QOID9MZqpyxWYlc/py2IvrBDjXv+vPDZz/lQIsjolTl+oPGQgjvX8DwxQ8+SWfRTwNQNifO+Wp8erJASTci+tgBN7Dm7qXR27UjMjozaEConnLY9nAE2i2ex4rGas7LoVW1Mi4XNd4cgg8ODnA0J8ZspBljuc2w1grb+jTdPA6LyjLSZyPoAj0tNkrmpk7W4AINqx7OkcLCSdNWfTzDB/5yCW5bauHwCpYQGWWjiv21IsFkkWGi8RTVy7YrDEn9gVtZKf8d37XX6YY/eYKVByUD2nBwRLgVRa/SjN2iMWMv/Pzne1hONilqYRMnjMK8iAJZ9SjTqHIjXOZfsmqy3xpGOWWuUKP7tiaSOtbjHCVJz5LKCNe/ra2QhueFD81tuqlltmZ+Mkeo9HDz9UrD9Q8sVO2bYRmxwpC4+hm9UUC57knENLFTPXYB6m/EC06a0wrJ82li/t6tB+GIuQBekMGnFzrdhelGsMeiPYJecwo4QUfHAwr5J9BY5T7z4kkz2FJXT38TGfvLw/zdSpX9++UOzMnQxXloXPHGyCw4c33RmzVXN2snrjRqtkitulFUwNfBGwu+oWulbHQ8nkviKox5tP9eTFQ0iPXYzWzSocwA==
    cookie-secret: AgAC1ytlYJFKUFL3vJjrCQxvOJ3v12kgH7yYrSSNbczLzY0oFNmD/dFpPX4ARpKqJcql1NojRQpjGKcT8C0XOGavVs/x+J6L+vq6N3azgB05JYH/7cyBbFsRE1iZGYv7vcWIQ90vmcZbiGjdWBX+s5cZchP1e6uScYEN7WZ+vUJtvu9qi/1unjf4TyKMIPwwMLOMsF0YOQcDahahYpAb9Rp+fRwHL5615LqZWrrbMcHhlp1Prc+Dxj1DbwSs86zMfUJz67XhWnnHHsJoMK6ICnUCaMlNNabve4ZJYpxGa1cknXErVRAvaqmOcs1fsfRKPNIn3Q8QlQvzvbLFpMLpRU7xTr9hX5P/zydiYT2u3NzA17KGWj9UAheq990LXOJ1kwAn5qkDzR8NbB1EfgnU84JyGgyGmfPJl8GC1yje8RsPIrNcS0Ahm9inKUUCP88Fvqrv3hFQqhYizOd0j/M4xGmZDTdm3DC8GdW0TgsEwU8Koivo5oSLkU746E6vKnKYUmfkre4aEWw4SjiLW4O0GED53wOM3DgaSzaZ+wignKoPV1mIP4dIyfos9QIpVyTsHscDCnJf1PgXwbpDRWcXwi4n5dlDZ5wjdPxgkYXUbVZOv6wgyV2Vfh7aIb9fZL8YKCxPolGIJjTzPzacvU0YMrfacBIcLXi70L0zG6xV/Q65uS7GGFe8sBZP+IuWmta84eB6O9S8SE8TOFDIp5mSgBK6xfQhfUNzz8xXxr2kUtqZWw==
  template:
    metadata:
      name: argocd-monitor-oauth
      namespace: argocd-monitor
