apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
{{- if eq (int .Values.service_port) 443 }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
{{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ if (kindIs "invalid" .Values.ssl_redirect) }}"true"{{ else }}{{ .Values.ssl_redirect | toString | quote }}{{ end }}
{{- if .Values.basic_auth | default false }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: admin-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
{{- end }}
{{- if .Values.oauth2_proxy | default false }}
    nginx.ingress.kubernetes.io/auth-url: "https://oauth2.{{ .Values.cluster_domain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://oauth2.{{ .Values.cluster_domain }}/oauth2/start?rd=$scheme://$host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email"
{{- end }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.name }}.{{ .Values.cluster_domain }}
      secretName: {{ .Values.name }}-secret
  rules:
    - host: {{ .Values.name }}.{{ .Values.cluster_domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.service_name }}
                port:
                  number: {{ .Values.service_port }}
