# use this to get to the grafana web UI if you have no ingress
- name: Create port forward script for Grafana
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/grafana.sh"
    content: |
      #!/bin/bash

      # Start a port-forward to the Grafana and background it
      nohup kubectl -n monitoring port-forward sts/grafana-prometheus 3000 &> /tmp/grafana-proxy.out &

      echo
      echo Grafana will be available at:
      echo   http://localhost:3000
    mode: "0755"

# use this to get to the ArgoCD web UI if you have no ingress
- name: Create port forward script for ArgoCD
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/argo.sh"
    content: |
      #!/bin/bash

      # # Start a port-forward to the ArgoCD and background it
      # nohup kubectl port-forward service/argocd-server -n argo-cd 8080:443 &

      # Get the initial admin password
      pass=$(kubectl -n argo-cd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)

      echo
      echo ArgoCD will be available at:
      echo   https://argocd.gkcluster.org
      echo   Username: admin
      echo   Initial Password: $pass

    mode: "0755"

# this script generates a token for the dashboard and starts a port-forward
# that can be used if there is no ingress
- name: Create dashboard connection script
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/dashboard.sh"
    content: |
      #!/bin/bash

      # Get the token for the dashboard
      echo Login Token:
      kubectl -n kubernetes-dashboard create token dashboard-admin
      echo
      echo URL: https://dashboard.gkcluster.org


      # # below is the port forward approach if no ingress/certs are available
      # # Start a port-forward to the dashboard and background it
      # nohup kubectl -n kubernetes-dashboard port-forward svc/kubernetes-dashboard-kong-proxy 8443:443 &> /tmp/k8s-dash-proxy.out &

      # echo
      # echo Dashboard will be available using above token at:
      # echo   https://localhost:8443
    mode: "0755"

- name: Create Longhorn connection script
  ansible.builtin.copy:
    dest: "{{ bin_dir }}/longhorn.sh"
    content: |
      #!/bin/bash

      echo Enter a New password for the Longhorn UI or leave blank to keep the current password
      read -s -p "Password: " pass
      if [[ -n $pass ]]; then
        echo -n "admin:$(echo -n {{ admin_password }}  | openssl passwd -stdin -apr1)" > /tmp/auth
        kubectl create secret generic basic-auth --from-file /tmp/auth -n longhorn
        rm /tmp/auth # could not work how to make this happen via environment variables
      fi

      # Start a port-forward to the Longhorn and background it
      nohup kubectl -n longhorn port-forward svc/longhorn-frontend 8090:80 &> /tmp/longhorn-proxy.out &

      echo
      echo Longhorn will be available at:
      echo   http://localhost:8090
    mode: "0755"
