apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-cluster-nfs
  namespace: backups
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: k8s-cluster-nfs
  resources:
    requests:
      storage: 500Gi
