apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: kubernetes
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        valuesObject:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          prometheus:
            enabled: true
          installCRDs: true
          ingressShim:
            defaultIssuerName: "letsencrypt-prod"
            defaultIssuerKind: "ClusterIssuer"
          # # https://cert-manager.io/v1.9-docs/usage/gateway/
          # extraArgs:
          #  - --feature-gates=ExperimentalGatewayAPISupport=true
    - path: ./kubernetes-services/additions/cert-manager
      repoURL: {{ .Values.repo_remote }}
      targetRevision: {{ .Values.repo_branch }}
      helm:
        valuesObject:
          domain_email: {{ .Values.domain_email | quote }}
          cluster_domain: {{ .Values.cluster_domain | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
