apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: echo
  project: kubernetes
  sources:
    - path: ./kubernetes-services/additions/echo
      repoURL: {{ .Values.repo_remote }}
      targetRevision: {{ .Values.repo_branch }}

    - path: ./kubernetes-services/additions/ingress
      repoURL: {{ .Values.repo_remote }}
      targetRevision: {{ .Values.repo_branch }}
      helm:
        valuesObject:
          name: echo
          cluster_domain: {{ .Values.cluster_domain }}
          service_name: echo-service
          service_port: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
