apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kernel-settings
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: kubernetes
  sources:
    - path: ./kubernetes-services/additions/kernel-settings
      repoURL: {{ .Values.repo_remote }}
      targetRevision: {{ .Values.repo_branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
