apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: matrix
  project: kubernetes
  sources:
    - chart: matrix-synapse
      targetRevision: 3.11.8
      repoURL: https://ananace.gitlab.io/charts
      valuesFiles:
        - ./kubernetes-services/additions/matrix/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
