apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: kubernetes
  sources:
    - path: argocd
      targetRevision: {{ .Values.minecraft_branch }}
      repoURL:  {{ .Values.minecraft_remote }}
      valuesObject:
        # Argo CD destination information
        destination:
          server: https://kubernetes.default.svc
          namespace: minecraft
        project: kubernetes # todo a separate project would be nice for this
        # pass down details so the child apps are also parameterized
        minecraft_remote: {{ .Values.minecraft_remote }}
        minecraft_branch: {{ .Values.minecraft_branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
