apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: minecaft
  sources:
    - path: argocd
      targetRevision: {{ .Values.minecraft_branch }}
      repoURL:  {{ .Values.minecraft_remote }}
      releaseName: minecraftRoot
      helm:
        valuesObject:
          # Argo CD destination information for the minecraft repo's root app
          project: minecraft
          destination:
            server: https://kubernetes.default.svc
            namespace: minecraft
          # also pass down repo details for the child apps
          minecraft_remote: {{ .Values.minecraft_remote }}
          minecraft_branch: {{ .Values.minecraft_branch }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
