- name: Extract the group that lists this turing pi's nodes
  ansible.builtin.set_fact:
    nodes: "{{ groups[inventory_hostname + '_nodes'] }}"

- name: List the nodes for '{{ inventory_hostname }}'
  ansible.builtin.debug:
    var: nodes

- name: Check if the control plane node is contactable
  ansible.builtin.include_tasks: node_status.yml
  vars:
    node_name: "{{ control_plane }}"

- name: Abort if user does not want to re-flash the control plane
  ansible.builtin.fail:
    msg: "User aborted the re-flash of the control plane"
  when: hostvars['localhost'].do_abort | default('y') != 'y'

- name: Process the nodes for '{{ inventory_hostname }}'
  ansible.builtin.include_tasks: node.yml
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node_name
