apiVersion: v1
kind: PersistentVolume
metadata:
  name: rkllama-models-nfs
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # don't delete NAS data if PVC is removed
  storageClassName: "" # static — not managed by any provisioner
  nfs:
    server: 192.168.1.3 # gknas
    path: /bigdisk/LMModels
  mountOptions:
    - vers=4.1
    - hard
