apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rkllama-models
  namespace: rkllama
spec:
  accessModes:
    - ReadWriteMany # Longhorn RWX — all DaemonSet pods share one models directory
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi
