# Setup ArgoCD to deploy the services defined in /kubernetes-services

- name: Install the helm chart for ArgoCD
  kubernetes.core.helm:
    chart_ref: oci://ghcr.io/argoproj/argo-helm/argo-cd
    chart_version: 7.8.3
    release_name: argocd
    namespace: argo-cd
    create_namespace: true
    values:
      controller:
        automountServiceAccountToken

- name: Add an ArgoCD Project for the cluster
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argo-cd/argo-project.yaml') }}"

- name: Add the Git Repo for the aboved project to track
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'argo-cd/argo-git-repository.yaml') }}"

# How to access

# 1. kubectl port-forward service/argocd-server -n argo-cd 8080:443
#     and then open the browser on http://localhost:8080 and accept the certificate
# 2. enable ingress in the values file `server.ingress.enabled` and either
#       - Add the annotation for ssl passthrough: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
#       - Set the `configs.params."server.insecure"` in the values file and terminate
# SSL at your ingress: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts

# After reaching the UI the first time you can login with username: admin and the random
# password generated during the installation. You can find the password by running:

# kubectl -n argo-cd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

# (You should delete the initial secret afterwards as suggested by the Getting Started
# Guide: https://argo-cd.readthedocs.io/en/stable/getting_started/#4-login-using-the-cli)