apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubernetes
  namespace: argo-cd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Services for the Turring Pi v2 Cluster

  # Restrict manifests to the project repo and trusted Helm chart registries
  sourceRepos:
    - "{{ repo_remote }}"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://charts.jetstack.io"
    - "https://kubernetes.github.io/ingress-nginx"
    - "https://kubernetes-sigs.github.io/headlamp/"
    - "https://helm.openwebui.com/"
    - "https://charts.longhorn.io/"
    - "https://nvidia.github.io/k8s-device-plugin"
    - "https://bitnami-labs.github.io/sealed-secrets"
    - "https://oauth2-proxy.github.io/manifests"

  # Allow manifests to deploy to any Namespace in this cluster
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

  # Allow all cluster-scoped resources to being created
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false
