apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-cluster-services
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: kubernetes
  source:
    path: ./kubernetes-services
    repoURL: >-
      {{ repo_remote }}
    targetRevision: >-
      {{ repo_branch }}
    helm:
      valuesObject:
        # pass down details so the child apps are also parameterized
        repo_remote: "{{ repo_remote }}"
        repo_branch: "{{ repo_branch }}"
        cluster_domain: "{{ cluster_domain }}"
        domain_email: "{{ domain_email }}"
        # TODO this is stored in plain-text in argocd values - switch to CAS
        admin_password: "{{ admin_password }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
