apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "argocd-ingress"
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argocd.{{ cluster_domain }}
      secretName: argocd-secret
  rules:
    - host: argocd.{{ cluster_domain }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: argocd-server
                port:
                  number: 443
