---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gbrain-secret
  namespace: gbrain
spec:
  encryptedData:
    DATABASE_URL: AgDkcBRdJeW22FisbGJElNOyCcO5mwiMREs2jE9c5frvjazK9y3abvlBMCYNrYU222fq6pR07Aq7eUx4A/pmfRNXSvV7u3n5/gxbXuVZi1I2aXgYTiJA0ZkHv57vczvPoUbvXXkMMHm9LY3NxmnVgr/GHZFkcixJaSJmhfMztpWhnWUQrrOJFQsiKqFTp7KWkzCvf/it8hbg3Ec5hZXrT5Uz95LMX0Tba0gveSdukuZEF9a8bePZS3ulpwWMwSrzo4r7rBfGTOxhcro2T7UC+/NaotZBpqDHVE30VWmLkCruU0Mqj4tcbNmXvb7qfl4Wu8n7kijkZM21fVK1Dz1nppQSf2PXq/UbPhH+A4O1osqa66rs4aoWlviY9zaYc4uJEVXJMBDHW16JgA5JzGpErT0Efk/oSspaNdCl33+HoJnDfW+b/QXk8pMiNnWZgVsZa58GMgQMYUGoP4k/LfYDXWK3Vpx/HEhR1GnWidJJUG4rh3uSQME8Luwww/ZJnJPWDhUjf4mCPo8qKDovLuaQibR+nTaeVY/0VUs8c2sx9hnGG+IkCpKwj0f1y9P9C8DczhYL/8W1YUPT7ss1lFgYv8wAI8ML9DW7Y7qDXx4SI+Hym/xWeSmOq1Pi3K93CLQ0PSdWBijWARPpZekDG2zdufiluj9tZnmqIMwiTeqREkAzS4NBPXLlk32eGmlM9Ar4salpV6HBWX2Jtnmn901zAkt7XqfWhqevbNsl4r8ZY3n0vLUNoIZUS8YhgX3ViysLGtORea5aOeIDsL58hVYQx/NJvqFYfx3HtMccSF0V2SRPXMCiUR9radWH+F7t436sAWMFHF/SeoGHSk8HbkRn9Qp1py5q2MzzrZVxvLp7WjxPnw==
    GBRAIN_ADMIN_BOOTSTRAP_TOKEN: AgC+I6GpB8gdT31H/xy0e7KZRKqy6XiXSxaxzqUETCYW05YBH6G8rE1VvW65tRk0vnEkGRze/Y9J6sMOFhsayTplNE1zu+thuSZkFXkLp+ouHpBAyQELSa0eUqBkkF8iun469LsGoJKu9Tufz6iF2RK9hPf2Zofce2Moh7ego23MmbIyuQBabEpnoGPIF51gfaKMsvnNWpM0nPAs9TmKrOLg/gMHpP0K+nDhEMMah4ESE86+ITSyTkRY/SxPXOutJZ/52ebA/2lTDxXOmGgrr8FJSz2py5uZ9+ehyBxNgh10RrMlDm4EUqAqWhu65mMxXdnNQQYesbV0LGQqJWc3f+kThQgDQdwA/Zt+3eIoy9dbXbWG6KeIiGtyi2lZDDh/3EsP36H1z+Z0D2/zWRqRvOuz0LZfPzmLsqdCng2NIHgwAyGd2+xfv3p9ih6o05DWInelPiPVPb9DGEdcpujsA/Sx9+8jEfBizCdwvdLJEbsCpWVYX41WG7ZqqC0mMW2/qCWe346tqAQDUeXrMpj2loTG7E2F/Lg+weD2UzAYaBAwGL6otDPg2DNIVjpzktAILiyDlXDEwVW6Z4/xSySwP2MwbxKFp2YxvXbJC+dWCaTKYxwrAa63nBs6cr/4K5/K3m5y/aIU13w96corFh/sQIhBYMSqT8gTpCK/Wc+n7c2w/HzKpe/ac+bB/W0p0w/pRmCkjBMHVECGP9RYxZamI7g6tuRj75vRzTw5frfHQ7nVfJzZZC9z1BJyrLbvj1IZt7sNRUWOIF6y603FciTXpW0G
  template:
    metadata:
      creationTimestamp: null
      name: gbrain-secret
      namespace: gbrain
